### PR TITLE
NSRangeException in setUnderlineForTabIndex on application load

### PR DESCRIPTION
**Pull request by sc0rch**
I don't dig too much into issue, but fix is working.

### CODE REVIEW

**Comment by bfeher** [comment]
Could you please explain to me why this library causes a 'crash on application load'? Is this something I can duplicate without manually attempting to select a nonexistent tab?

I'm not sure how I feel about this. On one hand it may prevent some crashes and make the library more fool-proof. On the other hand, it encourages bad design. Nobody should ever be trying to select/underline tabs that don't exist or are not currently displayed. A crash might help somebody find the mistake in their code which is causing them to erroneously select nonexistent tabs.

However, if this is fixing a bug in the library I'm totally for this merge. 

Thanks you.

**Comment by bfeher** [comment]
Ok I see you are helping to make the programmatic instantiation work. Unfortunately, while this does prevent the crash on startup, something is still wrong with how the BFPaperTabBarController gets setup. It has no tap circles or any of its Paper elements :(

I still haven't figured out how to properly get it working when instantiating it programmatically :(

**Comment by sc0rch** [comment]
Sorry for my English first.

You can reject the pull request, of course, it is not a problem, I've temporarily created the fork of repository to use in my project. We can wait for more appropriate bugfix.

I'm not sure, what do you mean as "programmatic instantiation".
Here the instantiation code from our project:
```
let newTabController = getViewControllerFromStoryboard(storyboardId) as! MainViewController

func getViewControllerFromStoryboard(viewControllerIdentifier: String) -> UIViewController {
  let storyboard = mainStoryboard()
  return storyboard.instantiateViewControllerWithIdentifier(viewControllerIdentifier)
}
```

Your TabBarController works perfectly after the fix, with all animations.
Short video: https://dl.dropboxusercontent.com/u/75848696/BFTabBarController.mp4

**Comment by bfeher** [comment]
Hi @sc0rch !

Thanks for the reply and the video!
Can you show me the code where you create the BFPaperTabBarController?

**Comment by sc0rch** [comment]
We have the ViewController in storyboard, associated with the MainViewController.
It has storyboard ID ("SB_MainViewController"), Tab Bar and Navigation Item.
I don't tried instantiate the tabs without storyboard or nib-file, sorry.
And we are using Swift language for applications.

Brief code of MainViewController:
```
class MainViewController: BFPaperTabBarController, UITabBarControllerDelegate {
  override func viewDidLoad() {
    super.viewDidLoad()
    ...
    self.tapCircleColor = UIColor.blackColor().colorWithAlphaComponent(0.15)
    self.showUnderline = false
  }
}
```

Instantiation:
```
func createMainInterface() -> MainViewController {
  // instantiating main tabs controller
  let mainViewController = getViewControllerFromStoryboard("SB_MainViewController")
      as! MainViewController // BFPaperTabViewController

  // creating tabs using the same method
  let tabMap     = createTabMap()
  let tabObjects = createTabObjects()
  let tabEvents  = createTabEvents()
  let tabSetup   = createTabSetup()

  mainViewController.viewControllers = [
      tabMap, tabObjects, tabEvents, tabSetup
  ]

  // somewhere later in code
  navigationController.viewControllers = [mainViewController]
}

// just main storyboard file access
func mainStoryboard() -> UIStoryboard {
  let storyboard = UIStoryboard(name: "Main", bundle: NSBundle.mainBundle())
  return storyboard
}

// just some sugar for view controller instantiation using storyboard identifier
func getViewControllerFromStoryboard(viewControllerIdentifier: String) -> UIViewController {
  let storyboard = mainStoryboard()
  return storyboard.instantiateViewControllerWithIdentifier(viewControllerIdentifier)
}
```


Also here is log when I'm commenting out the range check in setUnderlineForTabIndex:
```
INFO:  [LocalDataStore]: Connection established, database version: 6
INFO:  [LocalDataStore]: Database initialized, version 6
2016-01-22 11:07:13.404 MobitrackClientApp[69240:] <GMR/INFO> App measurement v.1201000 started
INFO:  [AccountDataManager]: Application key: Optional("b840e09d-feb6-4a06-921d-97014567c363")
2016-01-22 11:07:13.472 MobitrackClientApp[69240:16812807] WARNING: GoogleAnalytics 3.14 void GAIUncaughtExceptionHandler(NSException *) (GAIUncaughtExceptionHandler.m:48): Uncaught exception: *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
ERROR: [Application]: Application failed to register for remote notifications, error: Error Domain=NSCocoaErrorDomain Code=3010 "REMOTE_NOTIFICATION_SIMULATOR_NOT_SUPPORTED_NSERROR_DESCRIPTION" UserInfo={NSLocalizedDescription=REMOTE_NOTIFICATION_SIMULATOR_NOT_SUPPORTED_NSERROR_DESCRIPTION}
2016-01-22 11:07:18.487 MobitrackClientApp[69240:16812807] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e180e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000111b37deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e064404 -[__NSArrayM objectAtIndex:] + 212
	3   BFPaperTabBarController             0x000000010dc575a3 -[BFPaperTabBarController setUnderlineForTabIndex:animated:] + 83
	4   BFPaperTabBarController             0x000000010dc56c28 -[BFPaperTabBarController setShowUnderline:] + 1256
	5   BFPaperTabBarController             0x000000010dc562c8 -[BFPaperTabBarController setupBFPaperTabBarController] + 2312
	6   BFPaperTabBarController             0x000000010dc551ed -[BFPaperTabBarController initWithCoder:] + 141
	7   MobitrackClientApp                  0x000000010c4a2530 _TFC18MobitrackClientApp18MainViewControllercfMS0_FT5coderCSo7NSCoder_GSqS0__ + 656
	8   MobitrackClientApp                  0x000000010c4a25fd _TToFC18MobitrackClientApp18MainViewControllercfMS0_FT5coderCSo7NSCoder_GSqS0__ + 45
	9   UIKit                               0x00000001109997db -[UIClassSwapper initWithCoder:] + 241
	10  UIKit                               0x0000000110b6d822 UINibDecoderDecodeObjectForValue + 705
	11  UIKit                               0x0000000110b6d558 -[UINibDecoder decodeObjectForKey:] + 278
	12  UIKit                               0x00000001109994b1 -[UIRuntimeConnection initWithCoder:] + 180
	13  UIKit                               0x0000000110b6d822 UINibDecoderDecodeObjectForValue + 705
	14  UIKit                               0x0000000110b6d9e3 UINibDecoderDecodeObjectForValue + 1154
	15  UIKit                               0x0000000110b6d558 -[UINibDecoder decodeObjectForKey:] + 278
	16  UIKit                               0x00000001109986c3 -[UINib instantiateWithOwner:options:] + 1255
	17  UIKit                               0x0000000110d00c40 -[UIStoryboard instantiateViewControllerWithIdentifier:] + 181
	18  MobitrackClientApp                  0x000000010c33c43c _TFC18MobitrackClientApp15ModuleWireframe31getViewControllerFromStoryboardfS0_FSSCSo16UIViewController + 108
	19  MobitrackClientApp                  0x000000010c27e016 _TFC18MobitrackClientApp13MainWireframe19createMainInterfacefS0_FT_CS_18MainViewController + 150
	20  MobitrackClientApp                  0x000000010c27eb77 _TFC18MobitrackClientApp13MainWireframe30presentMainInterfaceFromWindowfS0_FCSo8UIWindowT_ + 39
	21  MobitrackClientApp                  0x000000010c2ef89a _TFFC18MobitrackClientApp15AppDependencies35installRootViewControllerIntoWindowFS0_FCSo8UIWindowT_U_FTGSqCS_7AppInfo_GSqCSo7NSError__T_ + 330
	22  MobitrackClientApp                  0x000000010c40aadb _TFFC18MobitrackClientApp18AccountDataManager12fetchAppInfoFS0_FFT6objectGSqCS_7AppInfo_5errorGSqCSo7NSError__T_T_U_FTGSqS1__CS_15LocalDataResult_T_ + 699
	23  MobitrackClientApp                  0x000000010c371e26 _TFC18MobitrackClientApp24LocalDataResourceManager15selectModelByIdu__Rdq_CS_5Model_fGS0_q__FTqd__17completionHandlerFT5modelGSqq__6resultCS_15LocalDataResult_T__T_ + 518
	24  MobitrackClientApp                  0x000000010c40a15e _TFC18MobitrackClientApp18AccountDataManager12fetchAppInfofS0_FFT6objectGSqCS_7AppInfo_5errorGSqCSo7NSError__T_T_ + 206
	25  MobitrackClientApp                  0x000000010c2eed92 _TFC18MobitrackClientApp15AppDependencies35installRootViewControllerIntoWindowfS0_FCSo8UIWindowT_ + 146
	26  MobitrackClientApp                  0x000000010c454fa4 _TFC18MobitrackClientApp11AppDelegate11applicationfS0_FTCSo13UIApplication29didFinishLaunchingWithOptionsGSqGVSs10DictionaryCSo8NSObjectPSs9AnyObject____Sb + 1828
	27  MobitrackClientApp                  0x000000010c4551b3 _TToFC18MobitrackClientApp11AppDelegate11applicationfS0_FTCSo13UIApplication29didFinishLaunchingWithOptionsGSqGVSs10DictionaryCSo8NSObjectPSs9AnyObject____Sb + 179
	28  UIKit                               0x00000001105d31f1 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 272
	29  UIKit                               0x00000001105d4397 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3415
	30  UIKit                               0x00000001105dacc6 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1760
	31  UIKit                               0x00000001105d7e7b -[UIApplication workspaceDidEndTransaction:] + 188
	32  FrontBoardServices                  0x0000000113a0f754 -[FBSSerialQueue _performNext] + 192
	33  FrontBoardServices                  0x0000000113a0fac2 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	34  CoreFoundation                      0x000000010e0aca31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	35  CoreFoundation                      0x000000010e0a295c __CFRunLoopDoSources0 + 556
	36  CoreFoundation                      0x000000010e0a1e13 __CFRunLoopRun + 867
	37  CoreFoundation                      0x000000010e0a1828 CFRunLoopRunSpecific + 488
	38  UIKit                               0x00000001105d77cd -[UIApplication _run] + 402
	39  UIKit                               0x00000001105dc610 UIApplicationMain + 171
	40  MobitrackClientApp                  0x000000010c4564ad main + 109
	41  libdyld.dylib                       0x000000011266792d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by bfeher** [comment]
Thank you for your help!

**Pull request merged**
