### PR TITLE
Added Top Line Bar functionality

### PR DESCRIPTION
**Pull request by onurvarrrr**
You can also show Top Line Bar instead of underline. Or you can also
show them both.

### CODE REVIEW

**Comment by onurvarrrr** [comment]
any improvement ?

**Comment by bfeher** [comment]
Hi @onurvarrrr 

I appreciate your addition but I couldn't add the pull because of a few issues. 

**Issue (grammar):**
`86|  /** A flag to set to YES to show a line bar on top of icon . If NO, they will not appear. (Default is NO) */`
**Fix:**
`86|  /** A flag to set to YES to show a line above the Tab Bar icon . If NO, it will not appear. (Default is NO) */`

**Issue (spelling):**
`87|  @property (nonatomic)  BOOL showTopLiner;`
**Fix:**
`87|  @property (nonatomic)  BOOL showTopLine;`

**Issue (code structure):**
`419|  #pragma mark - Tab Utility Methods`
**Fix:** This should be deleted because this section already exists above on line 386.


I'm sorry but I don't have time to hunt through and look for more mistakes, hopefully my initial pass caught them all. If you can clean these up and resubmit then I will reconsider.

Thank you.

**Comment by onurvarrrr** [comment]
Fixes are resubmitted

**Comment by bfeher** [comment]
Thank you.

**Comment by bfeher** [comment]
Hi, sorry I had to revert because after merging, at least 8 build errors appeared in BFPaperTabBarController.m

Please check your code and resubmit when the errors are fixed. Thanks.

**Pull request merged**
